name: Releases

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: ${{github.workspace}}/build/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

