name: Releases

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  include:
    - stage: compile linux assets and publish
      deploy:
        provider: releases
        <<: *deploy_base
        draft: true
