name: Releases

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Create a release
    - uses: actions/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

