name: Releases

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  release-linux:
    name: Create Github Release for linux
    runs-on: ubuntu-latest
    steps:
    - name: Create Release ${{ runner.os }}
      id: create_release_for_linux
      uses: actions/create-release@v1
      env:
        GHR_PATH: ${{github.workspace}}/linux/build/
      with:
        tag_name: ${{ runner.os }}${{ github.run_id }}
        release_name: Release for ${{ runner.os }} ${{ github.run_id }}
        draft: false
        prerelease: false
    - name: Output Release URL File
      run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt
    - name: Save Release URL File for publish
      uses: actions/upload-artifact@v1
      with:
        name: release_url
        path: release_url.txt

  release-windows:
    name: Create Github Release for windows
    runs-on: windows-2019
    steps:
    - name: Create Release ${{ runner.os }}
      id: create_release_for_windows
      uses: actions/create-release@v1
      env:
        GHR_PATH: ${{github.workspace}}/windows/build/
      with:
        tag_name: ${{ runner.os }}${{ github.run_id }}
        release_name: Release for ${{ runner.os }} ${{ github.run_id }}
        draft: false
        prerelease: false
    - name: Output Release URL File
      run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt
    - name: Save Release URL File for publish
      uses: actions/upload-artifact@v1
      with:
        name: release_url
        path: release_url.txt

  release-macos:
    name: Create Github Release for macos
    runs-on: macos-10.15
    steps:
    - name: Create Release ${{ runner.os }}
      id: create_release_for_macos
      uses: actions/create-release@v1
      env:
        GHR_PATH: ${{github.workspace}}\macos\build\
      with:
        tag_name: ${{ runner.os }}${{ github.run_id }}
        release_name: Release for ${{ runner.os }} ${{ github.run_id }}
        draft: false
        prerelease: false
    - name: Output Release URL File
      run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt
    - name: Save Release URL File for publish
      uses: actions/upload-artifact@v1
      with:
        name: release_url
        path: release_url.txt
